# -*- coding: utf-8 -*-
"""emotion_detection_model_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uANn88Jm7fiLzs2U182wp_b7ikW94C51
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,BatchNormalization, Dropout
from keras.models import Sequential

import zipfile
import os

zip_ref = zipfile.ZipFile('/content/archive.zip')
zip_ref.extractall('/content')
zip_ref.close()

train_data=keras.utils.image_dataset_from_directory(
    directory='/content/train',
    labels='inferred',
    batch_size=64,
    color_mode='grayscale',
    image_size=(128,128)
)
validation_data=keras.utils.image_dataset_from_directory(
    directory='/content/test',
    labels='inferred',
    color_mode='grayscale',
    batch_size=64,
    image_size=(128,128)
)

def process(image, label):
    image = tf.cast(image / 255., tf.float32)
    return image, label

train_data = train_data.map(process)
validation_data = validation_data.map(process)

model=Sequential()

model.add(keras.layers.RandomFlip("horizontal", input_shape=(128,128,1)))
# model.add(keras.layers.RandomRotation(0.1))
# model.add(keras.layers.RandomZoom(0.1))

model.add(Conv2D(64,kernel_size=(3,3),padding='same',activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))

model.add(Conv2D(128,kernel_size=(3,3),padding='same',activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))

model.add(Conv2D(128,kernel_size=(3,3),padding='same',activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2),padding='valid',strides=2))

model.add(Flatten())

model.add(Dense(128,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.3))
# model.add(Dense(32,activation='relu'))
# model.add(BatchNormalization())
# model.add(Dropout(0.4))
model.add(Dense(7,activation='softmax'))

model.summary()

from keras.callbacks import EarlyStopping,ReduceLROnPlateau
callback=EarlyStopping(
    monitor='val_accuracy',
    patience=8,
    restore_best_weights=True

)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4, min_lr=1e-5)

model.compile( loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(train_data,epochs=40,validation_data=validation_data,callbacks=[callback,reduce_lr])

test_loss, test_acc = model.evaluate(validation_data)
print(f"Restored Model - Val Loss: {test_loss:.4f}, Val Accuracy: {test_acc*100:.2f}%")

model.save('/content/emotion_model.h5')

class_names = train_data.class_names
print(class_names)

from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode
import cv2
import numpy as np
from tensorflow.keras.models import load_model

model = load_model('/content/emotion_model.h5')
class_names = ['angry', 'disgust', 'fear', 'happy', 'neutral', 'sad', 'surprise']

def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
            const div = document.createElement('div');
            const capture = document.createElement('button');
            capture.textContent = 'Capture';
            div.appendChild(capture);
            const video = document.createElement('video');
            video.style.display = 'block';
            const stream = await navigator.mediaDevices.getUserMedia({video: true});
            document.body.appendChild(div);
            div.appendChild(video);
            video.srcObject = stream;
            await video.play();
            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);
            await new Promise((resolve) => capture.onclick = resolve);
            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);
            stream.getVideoTracks()[0].stop();
            div.remove();
            return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])
    with open(filename, 'wb') as f:
        f.write(binary)
    return filename

def detect_emotion():
    filename = take_photo()

    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    img = cv2.imread(filename)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    if len(faces) == 0:
        print("Koi face detect nahi hua, dubara try karo.")
        return

    for (x, y, w, h) in faces:
        face = gray[y:y+h, x:x+w]
        face = cv2.resize(face, (128, 128))
        face = face / 255.0
        face = np.expand_dims(face, axis=(0, -1))

        pred = model.predict(face)
        emotion = class_names[np.argmax(pred)]
        confidence = np.max(pred) * 100

        cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(img, f'{emotion} ({confidence:.1f}%)', (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    from google.colab.patches import cv2_imshow
    cv2_imshow(img)


# ==================== LOOP: Jitni baar chaho capture karo ====================
while True:
    detect_emotion()
    again = input("Dobara capture karna hai? (y/n): ")
    if again.lower() != 'y':
        break